Imports

In [34]:
import numpy as np
np.set_printoptions(threshold=10000,suppress=True)
import pandas as pd
import warnings
import matplotlib
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')

Charger les données

In [35]:
# X : 4 premieres colonnes, y : 5eme colonne
data = pd.read_csv('data/iris.txt', header=None, sep='\t')
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values
print("X shape:", X.shape)
print("y shape:", y.shape)

# afficher la premiere ligne de X et y
print(X[:1])
print(y[:1])

X shape: (150, 4)
y shape: (150,)
[[5.1 3.5 1.4 0.2]]
[1]


Découpage de la base d'apprentissage

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=42, stratify=y)
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (100, 4)
X_test shape: (50, 4)


Implémentation d'un Perceptron Multi-classe

In [37]:
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score

clf = Perceptron(max_iter=1000, eta0=0.1, random_state=42)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

y_pred = clf.predict(X_test)

acc = accuracy_score(y_test, y_pred)
print(f"Accuracy: {acc:.2f}")


Accuracy: 0.80


In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

# Prédictions sur le jeu de test
y_pred = clf.predict(X_test)

# Matrice de confusion
cm = confusion_matrix(y_test, y_pred)
print("Matrice de confusion:")
print(cm)

# Accuracy globale
accuracy = accuracy_score(y_test, y_pred)
print(f"\nAccuracy globale: {accuracy:.4f}")

# Précision pour chaque classe
precision = precision_score(y_test, y_pred, average=None, zero_division=0)
print("\nPrécision par classe:")
for i, p in enumerate(precision):
    print(f"  Classe {i+1}: {p:.4f}")

# Rappel pour chaque classe
recall = recall_score(y_test, y_pred, average=None, zero_division=0)
print("\nRappel par classe:")
for i, r in enumerate(recall):
    print(f"  Classe {i+1}: {r:.4f}")

Matrice de confusion:
[[15  1  0]
 [ 0  8  9]
 [ 0  0 17]]

Accuracy globale: 0.8000

Précision par classe:
  Classe 1: 1.0000
  Classe 2: 0.8889
  Classe 3: 0.6538

Rappel par classe:
  Classe 1: 0.9375
  Classe 2: 0.4706
  Classe 3: 1.0000
