In [17]:
import numpy as np
np.set_printoptions(threshold=10000,suppress=True)
import pandas as pd
import warnings
import matplotlib
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')

In [18]:
# Chargement du fichier
data = np.loadtxt("data/Iris.txt", delimiter="\t", dtype=str)

# Séparation des variables
X = data[:, :4].astype(float)  # 4 premières colonnes
y = data[:, 4]                 # dernière colonne (cible)

print("X shape :", X.shape)
print(X)
print("y shape :", y.shape)
print(y)


X shape : (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.

In [19]:
from sklearn.model_selection import train_test_split

# Découpage stratifié
X_A, X_T, y_A, y_T = train_test_split(
    X, y,
    test_size=1/3,
    stratify=y,
    random_state=42
)

print("Taille apprentissage :", X_A.shape)
print("Taille test :", X_T.shape)


Taille apprentissage : (100, 4)
Taille test : (50, 4)


In [ ]:
from sklearn.linear_model import Perceptron
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

encoder = LabelEncoder()

y_A_enc = encoder.fit_transform(y_A)
y_T_enc = encoder.transform(y_T)

perceptron = Perceptron(
    max_iter=1000,
    eta0=0.1,
    random_state=42
)

perceptron.fit(X_A, y_A_enc)

y_pred = perceptron.predict(X_T)

accuracy = accuracy_score(y_T_enc, y_pred)
print("Accuracy globale :", accuracy)

conf_matrix = confusion_matrix(y_T_enc, y_pred)
print("Matrice de confusion :\n", conf_matrix)



Taux de reconnaissance : 0.8
[[15  1  0]
 [ 0  8  9]
 [ 0  0 17]]
